slam_toolbox:
  ros__parameters:
    use_sim_time: false

    odom_frame: "odom"
    map_frame:  "map"
    base_frame: "base_link"
    scan_topic: "/scan_reliable"

    # Keep a generous TF history window (seconds)
    tf_buffer_duration: 30.0
    transform_timeout: 1.0

    # LiDAR specifics
    min_laser_range: 0.2
    max_laser_range: 10.0

    #mode: "mapping"
    mode: "mapping"
    map_file_name: ""
    map_update_interval: 1.0
    resolution: 0.03  #meters per cell
    minimum_travel_distance: 0.05


# --- NEW PARAMETERS TO PREVENT JUMPING ---
    # These settings make the SLAM more stable by trusting the odometry more
    # and limiting how far it searches for a match.
    #transform_publish_period: 0.02 
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_scan_barycenter_change: 0.02
    loop_match_minimum_response_fine: 0.6
    loop_search_maximum_distance: 3.0
    # This is the most important one for reducing jumps
    solver_search_radius: 0.5